//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KütüphaneEntities : DbContext
    {
        public KütüphaneEntities()
            : base("name=KütüphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<CategoryBook> CategoryBook { get; set; }
        public virtual DbSet<Userbook> Userbook { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Writer> Writer { get; set; }
    }
}
